
tup.include('build.lua')

--FLAGS += '-Werror'
-- C-specific flags
FLAGS += '-D__weak="__attribute__((weak))"'
FLAGS += '-D__packed="__attribute__((__packed__))"'
FLAGS += '-DUSE_STDPERIPH_DRIVER'
FLAGS += '-DSTM32F40_41xxx'
FLAGS += '-D__FPU_PRESENT=1'
FLAGS += '-D__VFP_FP__'
FLAGS += '-DARM_MATH_CM4'
FLAGS += '-DARM_MATH_MATRIX_CHECK'
FLAGS += '-DARM_MATH_ROUNDING'

FLAGS += '-mthumb'
FLAGS += '-mcpu=cortex-m4'
FLAGS += '-mfpu=fpv4-sp-d16'
FLAGS += '-mfloat-abi=hard'
FLAGS += { '-Wall', '-Wfloat-conversion', '-fdata-sections', '-ffunction-sections'}

-- debug build
FLAGS += '-g -gdwarf-2'

boarddir = 'Gcc'

-- linker flags
LDFLAGS += '-T'..boarddir..'/STM32F405RGTx_FLASH.ld'
LDFLAGS += '-L'..boarddir..'/CMSIS/Lib' -- lib dir
LDFLAGS += '-lc -lm -lnosys -larm_cortexM4lf_math' -- libs
LDFLAGS += '-mthumb -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard  -specs=nosys.specs -specs=nano.specs -u _printf_float -u _scanf_float -Wl,--cref -Wl,--gc-sections'
LDFLAGS += '-Wl,--undefined=uxTopUsedPriority'


-- common flags for ASM, C and C++
OPT += '-O2'
OPT += '-ffast-math -fno-finite-math-only'
tup.append_table(FLAGS, OPT)
tup.append_table(LDFLAGS, OPT)

toolchain = GCCToolchain('arm-none-eabi-', 'build', FLAGS, LDFLAGS)

-- Load list of source files Makefile that was autogenerated by CubeMX
--[[
vars = parse_makefile_vars(boarddir..'/Makefile')
all_stm_sources = (vars['C_SOURCES'] or '')..' '..(vars['CPP_SOURCES'] or '')..' '..(vars['ASM_SOURCES'] or '')
for src in string.gmatch(all_stm_sources, "%S+") do
    stm_sources += boarddir..'/'..src
end
for src in string.gmatch(vars['C_INCLUDES'] or '', "%S+") do
    stm_includes += boarddir..'/'..string.sub(src, 3, -1) -- remove "-I" from each include path
end
]]--

build{
    name='AR5_Joint',
    toolchains={toolchain},
    packages={},
    sources={
        'Main/main.c',
        'EtherCAT/src/coeappl.c',
        'EtherCAT/src/ecatappl.c',
        'EtherCAT/src/ecatcoe.c',
        'EtherCAT/src/ecatslv.c',
        'EtherCAT/src/mailbox.c',
        'EtherCAT/src/objdef.c',
        'EtherCAT/src/sdoserv.c',
        'EtherCAT/src/SPI1.c',
        'EtherCAT/src/stm32f405hw.c',
        'EtherCAT/src/cia402appl.c',
        'StateMachine/Configuration.c',
        'StateMachine/Control.c',
        'StateMachine/M1_statemachine.c',
        'StateMachine/Motor_Drive.c',
        'StateMachine/StateMachine.c',
        'STM32_MODBUS/modbusCB.c',
        'STM32_MODBUS/modbus/mb.c',
        'STM32_MODBUS/modbus/ascii/mbascii.c',
        'STM32_MODBUS/modbus/functions/mbfunccoils.c',
        'STM32_MODBUS/modbus/functions/mbfuncdiag.c',
        'STM32_MODBUS/modbus/functions/mbfuncdisc.c',
        'STM32_MODBUS/modbus/functions/mbfuncholding.c',
        'STM32_MODBUS/modbus/functions/mbfuncinput.c',
        'STM32_MODBUS/modbus/functions/mbfuncother.c',
        'STM32_MODBUS/modbus/functions/mbutils.c',
        'STM32_MODBUS/modbus/port/portevent.c',
        'STM32_MODBUS/modbus/port/porttimer.c',
        'STM32_MODBUS/modbus/port/RS485portserial.c',
        'STM32_MODBUS/modbus/rtu/mbcrc.c',
        'STM32_MODBUS/modbus/rtu/mbrtu.c',
        'STM32_MODBUS/modbus/tcp/mbtcp.c',
        'Main/CRC_16.c',
        'Main/GlobalVariable.c',
        'Main/JC2JDCommunication.c',
        'Main/RS232_USART.c',
        'Main/RS485_DMA.c',
        'Main/RS485_JC2JD_ModBus.c',
        'Main/RS485_USART.c',
        'Main/stm32f4xx_it.c',
        'Gcc/startup_stm32f405xx.s',
        'STM32F4Driver/Sou/misc.c',
        'STM32F4Driver/Sou/stm32f4xx_adc.c',
        'STM32F4Driver/Sou/stm32f4xx_can.c',
        'STM32F4Driver/Sou/stm32f4xx_crc.c',
        'STM32F4Driver/Sou/stm32f4xx_dma.c',
        'STM32F4Driver/Sou/stm32f4xx_exti.c',
        'STM32F4Driver/Sou/stm32f4xx_flash.c',
        'STM32F4Driver/Sou/stm32f4xx_gpio.c',
        'STM32F4Driver/Sou/stm32f4xx_i2c.c',
        'STM32F4Driver/Sou/stm32f4xx_sdio.c',
        'STM32F4Driver/Sou/stm32f4xx_spi.c',
        'STM32F4Driver/Sou/stm32f4xx_tim.c',
        'STM32F4Driver/Sou/stm32f4xx_syscfg.c',
        'STM32F4Driver/Sou/stm32f4xx_usart.c',
        'STM32F4Driver/Sou/stm32f4xx_rcc.c',
        'STM32F4Driver/Sou/stm32f4xx_dbgmcu.c',
        'CMSISCore/Sou/system_stm32f4xx.c',
        'SystemViewer/SEGGER_RTT.c',
        'SystemViewer/SEGGER_SYSVIEW.c',
        'SystemViewer/SEGGER_SYSVIEW_Config_NoOS.c'
    },
    includes={
        'CMSISCore/Inc',
        'Gcc/CMSIS/Include',
        'Main',
        'SystemViewer',
        'StateMachine',
        'EtherCAT/Inc',
        'STM32_MODBUS/modbus/include',
        'STM32_MODBUS/modbus/ascii',
        'STM32_MODBUS/modbus/port',
        'STM32_MODBUS/modbus/rtu',
        'STM32_MODBUS/modbus/tcp',
        'STM32F4Driver/Inc',
        'STM32F4Driver/Inc'
    }
}
